### ISSUE TITLE
BHI Inaccuracies

### ISSUE THREAD

**Issue by XuteBox** [NaiNonTH/BHI#1]
## Describe the Issue:
The issues I found were the following: 
1. amethyst buds and clusters are always facing up
2.  small amethyst bud has smaller hit box than its actual hit box
3. drip stone tip has the hit box one pixel higher than its actual hit box

I have tried fixing these issues and linked the resource pack down below. 

## Screenshots:

1. Amethyst geode with the BHI V1.1.1

![image](https://github.com/NaiNonTH/BHI/assets/132842761/3164f0b2-f922-49c6-8f44-e686156fc7df)

1. Amethyst geode with the BHI Fixed

![image](https://github.com/NaiNonTH/BHI/assets/132842761/15083af8-4a0b-4add-8a01-103950fd26ab)

2. Small amethyst bud with the BHI V1.1.1

![image](https://github.com/NaiNonTH/BHI/assets/132842761/d7cebee4-9803-477c-8fbf-df4150c3e4e2)

2. Small amethyst bud with the BHI Fixed
![image](https://github.com/NaiNonTH/BHI/assets/132842761/ff9275a8-7ebc-4838-8d60-0f17f67084a9)

3. Dripstone with the BHI V1.1.1
![image](https://github.com/NaiNonTH/BHI/assets/132842761/44929591-9cb1-497b-a384-3f1d8a09e37e)

3. Dripstone with the BHI Fixed
![image](https://github.com/NaiNonTH/BHI/assets/132842761/b2fe60dc-ba82-464d-8c43-90a331ca7a77)

## Environment Details:
 - Minecraft Version: 1.20.1
 - Mods used: ![image](https://github.com/NaiNonTH/BHI/assets/132842761/0800c2da-af76-41ec-b32d-9a1bc9cdb0b9)
 - Resource Pack Version: V1.1.1

## Additional Details:
I tried fixing these issues as my friend wanted the pack. However, it is important to mention that I am NOT any resource pack expert and have made only one small overlay where I mostly just changed textures. So feel free to change the code I changed. More specifically I changed the .JSON files in models and blockstates for all of the amethyst buds and cluster aswell as dripstone with the number 0.

## The fixed version:
[Block Hitboxes Indicator Fixed.zip](https://github.com/NaiNonTH/BHI/files/14465518/Block.Hitboxes.Indicator.Fixed.zip)

**Comment by NaiNonTH** [comment]
Wow, I appreciate your hard work. I will release your fix. Thank you very much.
