### ISSUE TITLE
Invisible Lectern 

### ISSUE THREAD

**Issue by nebulajinxed** [NaiNonTH/BHI#2]
If a lectern is facing south (placed while looking north), then it is invisible.
But if the lectern contains a book the book is visible.
While looking into the code i noticed it also isnt working for east.
I have fixed them both, just replace the old lectern.json with this one.
[lectern.json](https://github.com/NaiNonTH/BHI/files/14501382/lectern.json)

// edit I just tested it but for some reason the lectern is still invisible for me.

**Comment by NaiNonTH** [comment]
Have you tried the 1.1.4? I think I've fixed that one.

**Comment by nebulajinxed** [comment]
I just relized that i was still using an older version. But thanks for the resposne

**Comment by NaiNonTH** [comment]
No problem :)
